#include "file_helper.c"
void makeNewFolder(char * folderName);
char *commandOpenFolder(char *name);
long getFileSize(FILE *f);
long sendFileSize(FILE *f,int sock);
void saveContentFile(int sock, char * action, char* filePath);
void sendContentFile(int sock,char * action,char *filePath);
int reciveFileSize(int sock);
void lower(char * str);
int yesNoQuestion(char * question);
int continueYesNo();
int checkFileExist(char *filename);
int checkFolderExist(char *folderName);
char *make_command_client(int comCode, char* attr1, char* attr2);
char* make_message(char*message,int check_file_exist);
char* make_message_folder(char*message);
char* make_download_file_command();
char* make_delete_file_command();
char* make_upload_file_command();
char* make_show_content_folder_command();
char* make_back_folder_command();
char* make_delete_folder_command();
char* make_open_folder_command();
char* make_new_folder_command();
int check_file_name_condition(char *filename);
int sendCommand(int sock,char *command);
command reciveRespond(int sock);
char* changeFilename(char *name);
void* changeNameToDifferrent(char *name);
char* changeFolderName(char * name);
char* getPathOfCurrentFolder(char *folder);
void changeFolderNameToDifferrence(char *name);
char* getPathOfCurrentFile();
void backFolder();
void* getAnyThingInFolder(char *folderPath,int sock);
void reciveNameOfFileAndFolder(int sock);